export const Action = {
    KML_FEATURES: "KML_FEATURES",
    FEATURES: "FEATURES",
    DELETE_KML_FEATURES: "DELETE_KML_FEATURES",
    MAP_CENTER: "MAP_CENTER",
};
export const Mutation = {
    KML_FEATURES: "KML_FEATURES",
    FEATURES: "FEATURES",
    DELETE_KML_FEATURES: "DELETE_KML_FEATURES",
    MAP_CENTER: "MAP_CENTER",
};