export const Action = {
    UBICACIONES: "UBICACIONES",
    UBICACIONES_ACT: "UBICACIONES_ACT",
    UBICACIONES_NEW: "UBICACIONES_NEW",
    UBICACIONES_DELETE: "UBICACIONES_DELETE",
    UBICACIONES_NEW_UPLOAD: "UBICACIONES_NEW_UPLOAD",
    UBICACIONES_DELETE_UPLOAD: "UBICACIONES_DELETE_UPLOAD",
};
export const Mutation = {
    UBICACIONES: "UBICACIONES",
    UBICACIONES_ACT: "UBICACIONES_ACT",
    UBICACIONES_NEW: "UBICACIONES_NEW",
    UBICACIONES_DELETE: "UBICACIONES_DELETE",
    UBICACIONES_NEW_UPLOAD: "UBICACIONES_NEW_UPLOAD",
    UBICACIONES_DELETE_UPLOAD: "UBICACIONES_DELETE_UPLOAD",
};